
logging:
  level:
    root: INFO

storage-app:
  blob-storages:
    - id: store1
      groupId: local
      classname: FileBlobStorage
      url: ../simple-storage-4j-ops-executor/config/store1
    - id: store2
      groupId: local
      classname: FileBlobStorage
      url: ../simple-storage-4j-ops-executor/config/store2

storage-app-server:
  periodicCheckSeconds: 30
  sessions:
    maxPingAliveSeconds: 180

  serverAuthHeaderName: api-key
  authApiKeys:
    - apiKey: dsfdfghsdmfj
      principal: test-executor
      authorities:
        - executor

  stateStorage:
    id: stateStorage
    groupId: local
    classname: FileBlobStorage
    url: config/stateStorage
