
storage-app:
  blob-storages:
    - id: store1
      groupId: local
      classname: FileBlobStorage
      url: ../simple-storage-4j-ops-executor/config/store1
    - id: store2
      groupId: local
      classname: FileBlobStorage
      url: ../simple-storage-4j-ops-executor/config/store2

storage-app-server:
  sessions:
    maxPingAliveSeconds: 240
    checkSessionAlivePeriodSeconds: 30

  serverAuthHeaderName: api-key
  authApiKeys:
    - apiKey: dsfdfghsdmfj
      principal: test-executor
      authorities:
        - executor
       