
storage-app:
  blob-storages:
    - id: store1
      groupId: local
      classname: FileBlobStorage
      url: ../simple-storage-4j-ops-executor/config/store1
    - id: store2
      groupId: local
      classname: FileBlobStorage
      url: ../simple-storage-4j-ops-executor/config/store2
      